### ISSUE TITLE
Configure CI to test with several versions of GHC

### ISSUE THREAD

**Issue by mrkkrp** [stackbuilders/harvest-api#2]
@jpvillaisaza, We need to make sure it works with at least the following GHC versions:
- 8.0.0
- 7.10.3
- 7.8.4
- 7.6.3 (can be dropped though)

**Comment by jpvillaisaza** [comment]
@mrkkrp We can cover 7.8.4 and 7.10.3 using CircleCI. I'm not sure about 8.0.1. Maybe we can, but it might be easier to switch to Travis CI (where we could allow failures for that particular one).

**Comment by jpvillaisaza** [comment]
Travis CI is activated for this project, so we can just add a .travis.yml file to switch.

**Comment by mrkkrp** [comment]
Done.
